# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scaleIncButton = QtWidgets.QPushButton(self.centralwidget)
        self.scaleIncButton.setObjectName("scaleIncButton")
        self.verticalLayout.addWidget(self.scaleIncButton)
        self.scaleDecButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleDecButton.sizePolicy().hasHeightForWidth())
        self.scaleDecButton.setSizePolicy(sizePolicy)
        self.scaleDecButton.setObjectName("scaleDecButton")
        self.verticalLayout.addWidget(self.scaleDecButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 4, 1, 1)
        self.vScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.vScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.vScrollBar.setObjectName("vScrollBar")
        self.gridLayout.addWidget(self.vScrollBar, 0, 0, 1, 1)
        self.pyqtgraphWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyqtgraphWidget.sizePolicy().hasHeightForWidth())
        self.pyqtgraphWidget.setSizePolicy(sizePolicy)
        self.pyqtgraphWidget.setObjectName("pyqtgraphWidget")
        self.gridLayout.addWidget(self.pyqtgraphWidget, 0, 1, 1, 1)
        self.hScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.hScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.hScrollBar.setObjectName("hScrollBar")
        self.gridLayout.addWidget(self.hScrollBar, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQtGraph"))
        self.scaleIncButton.setText(_translate("MainWindow", "Scale+"))
        self.scaleDecButton.setText(_translate("MainWindow", "Scale-"))
from pyqtgraph import PlotWidget
